env:
  global:
    # Run all cargo commands with --verbose.
    - CARGO_TERM_VERBOSE=true
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    # Deny all compiler warnings.
    - RUSTFLAGS="-D warnings"
os:
  - linux
  - osx
language: rust
rust:
  - stable
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt clippy
script:
  - set -x;
    cargo fmt -- --check &&
    ./scripts/clippy &&
    cargo test --verbose --release
before_cache:
  - cargo prune
